/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ServerOptions {
  port: number
  allowedCorsOrigins: Array<string>
}
export type ERPCServer = ErpcServer
export class ErpcServer {
  constructor(options: ServerOptions, types: Array<string>, enableSockets: boolean, role: string)
  run(): Promise<void>
  stop(): void
}
