/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ServerOptions {
  port: number
  allowedCorsOrigins: Array<string>
}
export interface TargetOptions {
  port: number
  address: string
}
export class ERPCServer {
  constructor(options: ServerOptions, types: Array<string>, enableSockets: boolean, role: string)
  /**
  * Starts the server as configured
  */
  run(): Promise<void>
  /**
  * Stops the server
  */
  stop(): void
}
export class ERPCTarget {
  constructor(options: TargetOptions, types: Array<string>)
}
